"""Build and verify the dependency-free Hermes dashboard bundle."""

from __future__ import annotations

import argparse
from pathlib import Path

DASHBOARD_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = DASHBOARD_ROOT / "frontend" / "src"
DIST_ROOT = DASHBOARD_ROOT / "dist"
SOURCE_FILES = (
    SOURCE_ROOT / "domain" / "state.js",
    SOURCE_ROOT / "infrastructure" / "api.js",
    SOURCE_ROOT / "application" / "state_polling.js",
    SOURCE_ROOT / "application" / "session_catalog.js",
    SOURCE_ROOT / "application" / "tuning_controller.js",
    SOURCE_ROOT / "application" / "state_controller.js",
    SOURCE_ROOT / "presentation" / "primitives.js",
    SOURCE_ROOT / "presentation" / "tuning_controls.js",
    SOURCE_ROOT / "presentation" / "state_view.js",
    SOURCE_ROOT / "presentation" / "session_navigator.js",
    SOURCE_ROOT / "presentation" / "page.js",
    SOURCE_ROOT / "index.js",
)
STYLE_SOURCE = SOURCE_ROOT / "presentation" / "style.css"
BUNDLE_PATH = DIST_ROOT / "index.js"
STYLE_PATH = DIST_ROOT / "style.css"


def build_bundle_text() -> str:
    header = """// Generated by dashboard/tools/build_dashboard.py. Do not edit directly.
(function () {
  \"use strict\";

  const SDK = window.__HERMES_PLUGIN_SDK__;
  const registry = window.__HERMES_PLUGINS__;
  if (!SDK || !registry) return;

  const feature = {};
"""
    body = "\n\n".join(path.read_text(encoding="utf-8").rstrip() for path in SOURCE_FILES)
    footer = "\n})();\n"
    return header + "\n" + body + footer


def build_style_text() -> str:
    return STYLE_SOURCE.read_text(encoding="utf-8").rstrip() + "\n"


def write_assets() -> None:
    DIST_ROOT.mkdir(parents=True, exist_ok=True)
    BUNDLE_PATH.write_text(build_bundle_text(), encoding="utf-8", newline="\n")
    STYLE_PATH.write_text(build_style_text(), encoding="utf-8", newline="\n")


def check_assets() -> bool:
    return (
        BUNDLE_PATH.is_file()
        and STYLE_PATH.is_file()
        and BUNDLE_PATH.read_text(encoding="utf-8") == build_bundle_text()
        and STYLE_PATH.read_text(encoding="utf-8") == build_style_text()
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated assets are stale")
    args = parser.parse_args()
    if args.check:
        if check_assets():
            print("Dashboard assets are current.")
            return 0
        print("Dashboard assets are stale. Re-run without --check.")
        return 1
    write_assets()
    bundle = BUNDLE_PATH.relative_to(DASHBOARD_ROOT)
    style = STYLE_PATH.relative_to(DASHBOARD_ROOT)
    print(f"Built {bundle} and {style}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
